/**
 * Route code generation utilities.
 * @module
 */

import {ScannedRoute} from './scanner.js';
import * as path from 'path';

/**
 * Options for route code generation.
 */
export interface CodegenOptions {
  /** The pages directory path */
  pagesDir: string;
  /** The output file path for generated routes */
  outputPath: string;
  /** Optional base path for routes */
  base?: string;
}

/**
 * Generates TypeScript code for route configuration from scanned routes.
 * The output exports a `routes` array compatible with the Bromium router.
 *
 * @param routes - Array of scanned route information
 * @param options - Code generation options
 * @returns Generated TypeScript source code
 *
 * @example
 * ```ts
 * const routes = scanPages('./src/pages');
 * const code = generateRouteConfig(routes, {
 *   pagesDir: './src/pages',
 *   outputPath: './src/routes.generated.ts',
 * });
 * fs.writeFileSync('./src/routes.generated.ts', code);
 * ```
 */
export function generateRouteConfig(
  routes: ScannedRoute[],
  options: CodegenOptions
): string {
  const { outputPath } = options;

  const outputDir = path.dirname(outputPath);

  const routeObjects: string[] = [];

  routes.forEach((route) => {
    let relativePath = path.relative(outputDir, route.filePath);
    relativePath = relativePath.replace(/\\/g, '/');

    relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');

    if (!relativePath.startsWith('.') && !relativePath.startsWith('/')) {
      relativePath = './' + relativePath;
    }

    let layoutImport = '';
    if (route.layoutPath) {
      let layoutRelativePath = path.relative(outputDir, route.layoutPath);
      layoutRelativePath = layoutRelativePath.replace(/\\/g, '/');
      layoutRelativePath = layoutRelativePath.replace(/\.(tsx?|jsx?)$/, '');
      if (!layoutRelativePath.startsWith('.') && !layoutRelativePath.startsWith('/')) {
        layoutRelativePath = './' + layoutRelativePath;
      }
      layoutImport = `,\n    layout: () => import('${layoutRelativePath}')`;
    }

    const routePath = route.routePath;

    const routeObj = `  {
    path: '${routePath}',
    component: () => import('${relativePath}')${layoutImport},
  }`;

    routeObjects.push(routeObj);
  });

  return `// Auto-generated by @bromscandium/vite-plugin
// Do not edit manually - changes will be overwritten

import type { Route } from '@bromscandium/router';

export const routes: Route[] = [
${routeObjects.join(',\n')}
];

export default routes;
`;
}

/**
 * Generates TypeScript type definitions for routes.
 * Provides type-safe route paths and parameter types.
 *
 * @param routes - Array of scanned route information
 * @returns Generated TypeScript declaration code
 *
 * @example
 * ```ts
 * const routes = scanPages('./src/pages');
 * const types = generateRouteTypes(routes);
 * fs.writeFileSync('./src/routes.generated.d.ts', types);
 * ```
 */
export function generateRouteTypes(routes: ScannedRoute[]): string {
  const routePaths = routes.map(r => `  | '${r.routePath}'`).join('\n');

  const paramTypes = routes
    .filter(r => r.params.length > 0)
    .map(r => {
      const params = r.params.map(p => `    ${p}: string;`).join('\n');
      return `  '${r.routePath}': {\n${params}\n  };`;
    })
    .join('\n');

  return `// Auto-generated route types

export type RoutePath =
${routePaths || "  | '/'"}

export interface RouteParams {
${paramTypes || "  '/': Record<string, never>;"}
}
`;
}
